### PR TITLE
Scripts/EasternKingdoms Arathi Highlands Alliance quests working, oth…

### PR DESCRIPTION
**Pull request by AussieGlenn**
…er adjustments

**Changes proposed:**

Alliance/Neutral quests only!

Fix one broken quest, multiple overspawns/adjustments

**Issues addressed:** Closes #  (insert issue tracker number)

**Tests performed:** (Does it build, tested in-game, etc.)

Compiled, tested with 2 characters

**Known issues and TODO list:** (add/remove lines as needed)

- [ ] 
- [ ]

### CODE REVIEW

**Comment by AussieGlenn** [comment]
Hi Traesh,

With quest 26049, using the item and intercepting the spell did not want to work, effect_ids not matching up, checked sniffs and DBC, but no amount of bashing would get it to work, so used a dummy with 10 yard radius to summon Myzrael, and it seems to work fine.

Note, with Myzrael this will need at least 3-4 characters with scaling and the SAI working properly, even with my 10% of normal damage cheat it was a close run thing.

Note, this will need more work when I finish all Alliance areas as there are Horde quests untested.

Thanks,

Glenn

**Comment by Traesh** [comment]
@AussieGlenn spell should be fixed now :)

So i removed the dummy npc, and even if i have absolutly no problem if you do dummies, be careful about the id you take, in that case it was a dummy from another quest item (https://fr.wowhead.com/item=33129), it could have lead to errors

**Comment by AussieGlenn** [comment]
Hi Traesh,

Should this line:

RegisterSpellScript(npc_myzrael_bunny);

be

RegisterSpellScript(spell_summon_myzrael);

?

Thanks,

Glenn

**Comment by leviathonbeast** [comment]
@AussieGlenn fixed.

**Comment by AussieGlenn** [comment]
Hi @leviathonbeast ,

Nope, at work still, will test and report back.

Thanks,

Glenn

**Pull request merged**
