### PR TITLE
Seat of the Triumvirate - L'ura enum.

### PR DESCRIPTION
**Pull request by ghost**
Hello. I know that you are now engaged in the Battle of Azeroth server. But suddenly it is useful.

**Changes proposed:**

-  Only L'ura encounter enum.
-  
-  

**Issues addressed:** Closes #  (insert issue tracker number)

**Tests performed:** (Does it build, tested in-game, etc.)

**Known issues and TODO list:** (add/remove lines as needed)

- [ ] 
- [ ]

### CODE REVIEW

**Comment by Ulduar** [comment]
@ReyDonovan почему бы и нет.

**Comment by Elgrimm** [comment]
Ооо Русские =)

**Comment by Elgrimm** [comment]
Не знаю почему но мне Легион всётаки прикипел =)

**Comment by Elgrimm** [comment]
Друзья, а у кого реализован Аватар падшего из ГС?

**Comment by ghost** [comment]
@Elgrimm i don't have any script for Fallen Avatar.

**Pull request closed without merging**
