### PR TITLE
Scripts/EasternKingdoms Loch Modan all quests fixed, no hacks

### PR DESCRIPTION
**Pull request by AussieGlenn**
**Changes proposed:**

All quests working in Loch Modan.

Fixed 6 broken quests plus miscellaneous fixes.

No hacks.

**Issues addressed:** Closes #  (insert issue tracker number)

**Tests performed:** (Does it build, tested in-game, etc.)
Compiled, tested with 2 different characters

**Known issues and TODO list:** (add/remove lines as needed)

- [ ] 
- [ ]

### CODE REVIEW

**Comment by AussieGlenn** [comment]
Hi Traesh,

The only concern I have is https://www.wowhead.com/npc=44572/skystrider

I summon it on quest accept, the exhaust flames are running, but i just cannot get it to be boarded or treated as a vehicle.

Going to the quest end point completes it normally so the quest is working.

As usual, make whatever changes you see fit.

Thanks,

Glenn

**Comment by wormogo** [comment]
Do you use spell 83980?

Vehicle_trmplate_accessories contains a seat definition? Does creature set a vehicleid?

These are my thoughts, i was fuxed this quest until mount with player. I can search for that fix

**Comment by AussieGlenn** [comment]
Hi Wormogo,

https://www.wowhead.com/spell=83980/summon-skystrider

This is to summon.

https://www.wowhead.com/spell=83984/skystrider-exhaust-flames

This is to add the exhaust flames to the Skystrider.

Unfortunately I have no Loch Modan sniffs, so had to try and guess the VehicleId, without any luck, so you cannot board it. If you can ride it, then I can write the flight path via rough guesses from youtube videos.

Thanks,

Glenn

**Comment by AussieGlenn** [comment]
Hi All,

Thanks so much to everyone who helped with sniffs, and how to interpret the vehicleid, it now works fine.

Thanks,

Glenn

**Pull request merged**
