### PR TITLE
Core/Scripts: Legion instance/world entrances and exits

### PR DESCRIPTION
**Pull request by Eredar**
**Changes proposed:**

-  Add entrances through trigger npcs with range checks (hack).

**Target branch(es):** 

- [x] master

**Issues addressed:** 

**Tests performed:** build, tested in-game

**Known issues and TODO list:** (add/remove lines as needed)
 Range check of some portals maybe.

### CODE REVIEW

**Comment by Seyden** [comment]
Blizz uses serverside areatrigger for it.. why shouldn't they?

**Comment by Eredar** [comment]
@Seyden I tried to find any areatriggers related to teleports in sniffs and didn't find a single one. There were only spell areatriggers or maybe TC sniff parser can't catch them. So I guess it's gameobjects (portals), but since FindNearestPlayer function not implemented for gobjects I did this with trigger npcs. They work just fine, so I guess it's not really matter.

**Comment by Seyden** [comment]
There aren't any areatriggers in the sniff, because the areatriggers are SERVER SIDE, blizzard doesn't send them

**Comment by Eredar** [comment]
@Seyden ok, got it, Traesh explained it to me few mins earlier, I'll leave it open because he said he will convert it to areatriggers.

**Pull request merged**
