### PR TITLE
Fix - blizz the quest Sacrifices

### PR DESCRIPTION
**Pull request by sergemanuel**
**Changes proposed:**
-  Fix - blizz the quest Sacrifices

**Tests performed:** 
build, tested in-game

**Known issues and TODO list:** (add/remove lines as needed)

- [ ] 
- [ ]

### CODE REVIEW

**Comment by sergemanuel** [comment]
The Travis CI build failed because spell.cpp, nothing to do with this fix, i supouse the error was there when i made the fork.

**Comment by cooler-SAI** [comment]
u can use SAI for summon the Horse

**Comment by sergemanuel** [comment]
for now is a solution, after can be rewrite that part on SAI, but i dont see why not in core like many others.
salute.

**Comment by sergemanuel** [comment]
@cooler-SAI , forget to tell you when you ask me, because I was in a hurry to go to work.
I decided to cast the spell in the core because that npc had a script in core that does other things, not even sure that an npc can have smartAI and ScriptName at the same time. I think that if the npc already has a script in the core it can be used.
Greetings.

**Comment by cooler-SAI** [comment]
@sergemanuel good job,man

**Pull request merged**
