### PR TITLE
Scripts/EasternKingdoms Duskwood quests/spawns fixed, but needs more …

### PR DESCRIPTION
**Pull request by AussieGlenn**
…work for 2 non-working quests

**Changes proposed:**

Fix every Duskwood quest
Adjust spawns/other changes

Credit to @Caydan for some scripts, thanks very much.

**Issues addressed:** Closes #  (insert issue tracker number)

**Tests performed:** (Does it build, tested in-game, etc.)
Compiled, tested with 2 characters

**Known issues and TODO list:** (add/remove lines as needed)

### CODE REVIEW

**Comment by AussieGlenn** [comment]
Hi Traesh/everyone,

There are two non-working quests, and this should not be committed until these are working.

If someone can patch the files so I can get

1. The https://www.wowhead.com/spell=82029/call-stalvan to cast
2. The https://www.wowhead.com/quest=26760/cry-for-the-moon quest to be offered

Then I can complete the scripts and do more testing.

All other quests apart from these two working.

Thanks,

Glenn

**Comment by leviathonbeast** [comment]
the quest should be offered after completing the previous steps in the chain are you not going through the chain correctly when you test?

https://www.youtube.com/watch?v=Rr7psKIfmtE

looks like some work for you there :D

**Comment by Traesh** [comment]
AussieGlenn : You should spawn gameobject 301070 in order to be able to cast 82029

You can then make a ZoneScript for Duskwood (Example : https://github.com/AshamaneProject/AshamaneCore/blob/master/src/server/scripts/BrokenIsles/zone_dalaran_legion.cpp#L210) and override method

void ProcessEvent(WorldObject* /*obj*/, uint32 /*eventId*/) { }

Check for eventId 25759 and obj will be the focus gameobject, 301070. From there you can spawn stalvan in that method

**Comment by AussieGlenn** [comment]
Hi @leviathonbeast ,

I had the chain set, removed it trying to get it to work.

Right now, there are no restrictions on that quest, and it will still not offer it.

Maybe there is a debug command to work out why?

Hi @Traesh ,

I will trace that in my morning, and follow your guide.

Thanks,

Glenn

**Comment by AussieGlenn** [comment]
Hi Traesh,

The spellfocus gameobject was exactly the fix, the two sniffs I had do not have it at all.

Now to bash this quest again to see if it will be offered.

Thanks,

Glenn

**Comment by AussieGlenn** [comment]
Hi Traesh,

This is ready to go, please make any adjustments you see fit.

Thanks,

Glenn

**Pull request merged**
