### PR TITLE
DB/Misc:a Lot of fixes in the world - stats,Quests,SAI

### PR DESCRIPTION
**Pull request by cooler-SAI**
**Changes proposed:**
a Lot of fixes in the world - stats,Quests,SAI
-  
-  
-  

**Issues addressed:** Closes #  (insert issue tracker number)

**Tests performed:** (Does it build, tested in-game, etc.)

**Known issues and TODO list:** (add/remove lines as needed)

- [ ] 
- [ ]

### CODE REVIEW

**Comment by Traesh** [comment]
Is there any GUID related stuff in there ?

And small curiosity of mine, why wasn't it merged with TDB ?

**Comment by Traesh** [comment]
Are you willing to support and update theses scripts ?

The point of this question is to know if i can just make a big merged .sql file, or if i take some times to keep them separate & make world server update from this folder as well

**Comment by cooler-SAI** [comment]
@Traesh , you can add all SmartAI from patch folder first to DB, then apply my misc fixes. I'll add new updates as soon as I can. This SMARtAI scripts from patch folder doesn't need to update. They are ready to go!

**Comment by lorac2k14** [comment]
Very Nice work @cooler-SAI  I just used your patches on db on my side, Awesome work 👍 
@Traesh Do you need a SQL Dump? What is your preference on dumping it If you want it?
Generally I dump at a table level so my updater pushes each table but i can use mysql to dump it if you need it, or any other style just mention it and ill get it done. 
Also Beautiful work on the core @Traesh and Team! :heartpulse: Thank you for what you do. You guys are amazing!

**Pull request closed without merging**
