### PR TITLE
Scripts/EasternKingdoms Fix Quest 26322 Rise of the Brotherhood

### PR DESCRIPTION
**Pull request by AussieGlenn**
**Changes proposed:**
Fix Quest 26322

**Issues addressed:** Closes #  (insert issue tracker number)
Quest 26322 Uncompleteable, there is a script, but it did not work, and needed some bashing

**Tests performed:** (Does it build, tested in-game, etc.)
Compiled and tested

**Known issues and TODO list:** (add/remove lines as needed)

- [ ] 
- [ ]

### CODE REVIEW

**Comment by AussieGlenn** [comment]
Hi Traesh,

Can you remove this line please?

char playername;

I was fiddling trying to get the player name working.

Also, make any other changes you see fit.

Thanks,

Glenn

**Comment by AussieGlenn** [comment]
Hi Artamedes,

Yes, this could be done, however the text hack was already in the existing script as is.

I am doing a minimal code change to get the quest working using the existing script.

Also, the broadcast_text is not present for Hope Saldean, so it will be a non-minor fix.

However, it can be done if required.

Thanks,

Glenn

**Comment by Artamedes** [comment]
Maybe soon if I get around to setting up a local ashamane tommorow i'll rescript this quest :D

**Comment by AussieGlenn** [comment]
Hi Artamedes,

Would you be ok making a new PR for your changes and allowing this PR to go through?

It now works, allowing a previously broken quest to be completed, and will allow me to continue with fixing quests.

Thanks,

Glenn

**Comment by Artamedes** [comment]
of course

**Comment by Traesh** [comment]
Tested it and it work great, the only problem is that everyone see the same spawns, and that the NPCs disappear after, blocking every other player from doing their quests ^^

I'm gonna see how we can make those personal

**Comment by AussieGlenn** [comment]
Hi Traesh,

More testing on this.

If you wait about 1-2 minutes after the event, all the NPCs are respawned back to their original position, i.e Hope, Ripsnarl, etc

So it seem to be multi-player functional, though personal spawns would be preferable.

Thanks,

Glenn

**Comment by Traesh** [comment]
I'll merge this for now as i don't have time to check for personal spawn, if the NPC respawn it's fine for now x)

**Pull request merged**
