### PR TITLE
Script  the whole Wondering island (Work from Lopfest for trinity)

### PR DESCRIPTION
**Pull request by HannibalRoG**
**Changes proposed:**

-  Replace the current WonderingIsland zone with the one created by @Lopfest for Trinity

**Issues addressed:** Closes #  (insert issue tracker number)
All issues about this zone can be closed :)

**Tests performed:** (Does it build, tested in-game, etc.)
Compiled
Tested the original PR in game, look completly blizzard.

**Known issues and TODO list:** (add/remove lines as needed)

This TODO its not for this PR but depend of it.
- [ ]
- [ ]

### CODE REVIEW

**Comment by Crandalius** [comment]
Are you sure you tested this?

**Comment by HannibalRoG** [comment]
Yes, it need some work to adapt to AshamaneCore.

**Comment by leviathonbeast** [comment]
hannibal are you still working on this?

**Comment by zamalaev** [comment]
@leviathonbeast
https://github.com/ProjectLegion/ProjectLegion/commit/6fad7856723fb4952a0718a1189d00a2484b884b

**Comment by Traesh** [comment]
Critical Bugs

- [ ] Weapon racks not working for monks
- [ ] Panda help each other in the first builder

Visual Bugs :

- [ ] Training target fight back & can move
- [ ] Pandas does not hit training targets & does not follow instructor movements
- [ ] Master's flame (player should be able to right click it to get it)

**Comment by Lopfest** [comment]
@Traesh
Master's flame (player should be able to right click it to get it) - not true since WoD. [Link](http://www.wowhead.com/quest=29408/the-lesson-of-the-burning-scroll#comments:id=1998871)
(other reports not applicable to original work on TC, except one)

**Comment by Traesh** [comment]
You're right about Master's flame. I deleted it from the list

**Comment by HannibalRoG** [comment]
Ahh my friend @lopfest, can you help in adapt to AshamaneCore?

**Comment by zamalaev** [comment]
@HannibalRoG all works fine there are small bugs with phases

**Comment by HannibalRoG** [comment]
@zgn1988 You are welcome to fix it ;)

**Comment by Traesh** [comment]
fixed some issue by setting SmartScript on good creature_template on Pandaren branch

**Comment by Traesh** [comment]
I close this as it have mostly be mergerd with branch Pandaren

**Pull request closed without merging**
