### PR TITLE
Fixed power consume Issue

### PR DESCRIPTION
**Pull request by AzgathCore**
Changes proposed:

- Fixed power consume Issue
- Powers will be used now

Target branch(es): 3.3.5/master

[ ] 3.3.5
[x] master

Issues addressed: Closes #24315 (insert issue tracker number)

Tests performed: (Does it build, tested in-game, etc.)

Tested Building
Tested Ingame

Known issues and TODO list: (add/remove lines as needed)
By @DuelistRag3

### CODE REVIEW

**Comment by DuelistRag3** [comment]
Thanks for the Tag there <3

**Comment by DuelistRag3** [comment]
Is it intendet that you renamed the header in the readme file? ^^

**Comment by AzgathCore** [comment]
> Is it intendet that you renamed the header in the readme file? ^^

If the permissions allow me, why not ^^

**Comment by AzgathCore** [comment]
> Thanks for the Tag there <3

With great pleasure :)

**Comment by DuelistRag3** [comment]
> > Is it intendet that you renamed the header in the readme file? ^^
> 
> If the permissions allow me, why not ^^

True :D

**Comment by mcsescott** [comment]
Good updates, and I appreciate that.

However, I would deny this ... it includes a lot of "Azgath" stuff.    That is perfectly fine on your own server, but shouldn't be changes on Ashamane core.

**Comment by DuelistRag3** [comment]
> Good updates, and I appreciate that.
> 
> However, I would deny this ... it includes a lot of "Azgath" stuff. That is perfectly fine on your own server, but shouldn't be changes on Ashamane core.

Ashamane and Trinitycore are not for server use mainly, they are educational software, so it does not matter what header it uses, and u can change it by urself any time

**Comment by mcsescott** [comment]
> Ashamane and Trinitycore are not for server use mainly, they are educational software, so it does not matter what header it uses, and u can change it by urself any time

Completely understood and agree, but "Azgath" branding should not be on the Ashamane Core.  I do think all the other changes are fine, though.  Good stuff.

**Comment by leviathonbeast** [comment]
This PR will not be merged while there are not required edits to the worldserver config/readme

**Comment by DuelistRag3** [comment]
Then just take out all azgathcore stuff or i will remake this pr @AzgathCore

**Comment by AzgathCore** [comment]
Hello to you

I'm new to GitHub so if you tell me I need to change the readme and configuration I'm ready to do it and update AzgathCore as often as possible :)

**Comment by AzgathCore** [comment]
Hello to you

I'm new to GitHub so if you tell me I need to change the readme and configuration I'm ready to do it and update AzgathCore as often as possible :)

**Comment by DuelistRag3** [comment]
You can just redo the changes you did to the banner and the readme and do a new commit into this pulll request (and of course reopen it)

**Pull request closed without merging**
